### PR TITLE
Codeigniter Composer Ready

### PR DESCRIPTION
**Pull request by Hanisch-IT**
In this PR i created the Restserver as composer ready and as possibility for include in library.

But now there is a namespace. I Think we can remove it to have backward compatibility but its a bit dirty. What do you think?

### CODE REVIEW

**Comment by chriskacerguis** [comment]
This is GREAT.  Thank you so much for it.  Do you think you can add an update to the README on how to install it?

**Comment by farukgaric** [comment]
Hi guys,
I use it with composer some time but I don't have time to make pull request.
If we use codeigniter as dependency we have to change $system_path in index.php.
`$system_path = 'vendor/codeigniter/framework/system';`

**Comment by Hanisch-IT** [comment]
Hi @farukgaric,

thats right but thats not a part of this package. If you want to use this package with composer you need to update your config.php file to set the vendor autoload. Additional you need to set your paths in the index.php of your project.

I Recommend to use https://github.com/kenjis/codeigniter-composer-installer to install codeigniter via composer. The advantage of this: Given folder structure.

**Comment by farukgaric** [comment]
Hi @Hanisch-IT ,

You're right! I also use CI composer installer but for me is hard to update restserver with these community changes because I changed some parts of REST_Controller and added JWT authentication. I am willing to contribute to this library!

**Comment by Hanisch-IT** [comment]
Hi @chriskacerguis,

i did all changes now. Its now installable with composer and without namespaces so it has the backward compatibility. Please check the changes.

**Comment by farukgaric** [comment]
@Hanisch-IT 
In README.md you have typo - check the last word in this quote.
`CodeIgniter Rest Server is available on Packagist (using semantic versioning), and installation via composer is the recommended way to install Kraken-api.`

**Comment by Hanisch-IT** [comment]
@farukgaric thank you. Will fix this. (damn C&P)

**Pull request merged**
