### PR TITLE
Dev abstract class initilized error

### PR DESCRIPTION
**Pull request by Cecilina**
abstract class initilized error using trait and interface

### CODE REVIEW

**Comment by luckydonald** [comment]
Interesting.

**Comment by chriskacerguis** [comment]
Could you please address the merge conflicts, and I'd be happy to merge.

**Comment by luckydonald** [comment]
Using `REST_Controller_Definitions::HTTP_OK` instead of `self::HTTP_OK` is not only way longer to type, and a strange mix of CamelCase and snake_case, it also breaks compatibility.

**Comment by Cecilina** [comment]
> Could you please address the merge conflicts, and I'd be happy to merge.

Hi @chriskacerguis,
After I created this PR, my team leader ask to create a new PR with our organization account. so a duplicated PR created for this issue, https://github.com/chriskacerguis/codeigniter-restserver/pull/997. since that one has already merged, I guess we can close this issue. Thanks!

**Pull request closed without merging**
