### PR TITLE
API calls time limit

### PR DESCRIPTION
**Pull request by lagaisse**
API calls time limit is now configurable.
Example:
```
$this->methods = ['methodname_get' => ['level' => 0, 'limit' => 1, 'time' => 60 * 60 * 24]];
```
Limit doesn't depend on url extension (doesn't solve #397 )

### CODE REVIEW

**Comment by lagaisse** [comment]
I did some modification but perhaps not enough. regarding CI3 style guide, it says all || should be replaced by OR.
but a few commits ago 7b69e66 , all OR were replaced by ||...

**Comment by mrfrogcoder** [comment]
nice one

**Comment by softwarespot** [comment]
@lagaisse, you make a valid point. Though that is one part of the style guide I tend to disagree with, even though I am used to using And & Or in AutoIt (BASIC-like language).

OR I would argue is for control flow and || for boolean logic. Also the comment about || looking like 11 surprises me, especially if you use a font like Source Code Pro.

**Comment by lagaisse** [comment]
I agree with you but "it's best we stick to the conventions of CI3" :) 
The best would be to remember the coding style AND the exceptions to the CI recommendations in the readme. What do you think?
As it's not the main subject of this PR we should open a new ticket

**Comment by softwarespot** [comment]
Is it possible to re-create again? Thanks

**Comment by lagaisse** [comment]
I did it three times because of coding style changes. So no, sorry.

**Comment by softwarespot** [comment]
Oh well, shame.

**Pull request closed without merging**
