### PR TITLE
Improvements with non-English developers in mind

### PR DESCRIPTION
**Pull request by softwarespot**
Now language strings are in an associative array, instead of being hardcoded.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
For language things, I'm wondering if we should use the CI Language Library instead of config.php.  Thoughts?  

Reference: http://www.codeigniter.com/user_guide/libraries/language.html

**Comment by softwarespot** [comment]
We should be and I did ask about this in the issue tracker, but no one responded. So I came up with this quick hack for the meantime.

**Comment by chriskacerguis** [comment]
Totally missed it, my bad.  If you want to update this PR with the lang files, I'll merge.  Still waiting for your DM :)

**Comment by softwarespot** [comment]
I don't have twitter and can't direct message you on github. I am cool with this setup.

I have updated the PR. Thanks

**Comment by softwarespot** [comment]
I will also do the docs now.

**Comment by softwarespot** [comment]
Done. I can't send you a DM as I don't have twitter and I unable to do it on github.com. I am cool with this setup =)

**Pull request merged**
