### PR TITLE
Composer support

### LINKED ISSUE #387: Add compatibility with Composer
Hi. First of all thank you for this module, it's a great job.

I would like to suggest to add the compatibility with [Composer](https://getcomposer.org), a dependency manager for PHP.

#### Add Composer

You just have to add a `composer.json` file in the root directory that could contain :
```javascript
{
	"description" : "A fully RESTful server implementation for CodeIgniter using one library, one config file and one controller",
	"name" : "chriskacerguis/codeigniter-restserver",
	"license": "MIT",
	"require": {
		"php": ">=5.2"
	}
}
```
and submit the package to https://packagist.org.

However, to do it in a clean way, you should keep only the files of RestServer:
```
application/config/rest.php
application/libraries/Format.php
application/libraries/REST_Controller.php
```
and **delete all the files of CodeIgniter**.

Moreover, CodeIgniter is compatible with [third_party packages](http://www.codeigniter.com/userguide3/libraries/loader.html#application-packages) since at least v2.
It allows to include packages that are not necessarily in the `application/third_party` folder and thus to include the folder of RestServer downloaded by Composer.

So, I think the best file organisation for this repository to respect CodeIgniter's third_party package will be:
```
config/rest.php
libraries/Format.php
libraries/REST_Controller.php
composer.json
LICENSE.txt
README.md
```

#### Expected installation
To install RestServer by Composer, you will just have to add this repository to the `composer.json` require field or run `composer require`. Then you need to run `composer install` to download the packages.
It will download RestServer to the vendor folder `vendor/chriskacerguis/codeigniter-restserver`.

To install RestServer in CodeIgniter, you should autoload it by adding its path to the `$autoload['packages']` array in `application/config/autoload.php`:
```php
/*
| -------------------------------------------------------------------
|  Auto-load Packages
| -------------------------------------------------------------------
| Prototype:
|
|  $autoload['packages'] = array(APPPATH.'third_party', '/usr/local/shared');
|
*/

$autoload['packages'] = array(APPPATH.'/../vendor/chriskacerguis/codeigniter-restserver');
```

Then in the controllers that extend `Rest_Controller`, you should set the require to:
```php
require(APPPATH.'../vendor/chriskacerguis/codeigniter-restserver/libraries/REST_Controller.php');

class User extends REST_Controller {
```

If you want to change the config of RestServer, simply copy `vendor/chriskacerguis/codeigniter-restserver/config/rest.php` to your `application/config` folder and start modifying it here.

#### More
I really hope that you add the compatibility with Composer.
I can also send a PR with the modifications described in this issue.

Thank you.

### PR DESCRIPTION
**Pull request by anthonysomerset**
This duplicates and fixes #387 

I've tried to take the approach that involves the least amount of changes or action required by the end user when using composer and also doesn't break manual installs

The readme documents full install process for composer but basically:
- Require the package in composer
- Update autoload.php to load the package (also update config.php if you need to enable composer loading)
- Define your controllers (without the additional `require_once`)

Some other "possible" breaking changes are that i have copied the application folder to example and then removed everything that absolutely isn't necessary for the package to function, e.g. example controllers and routes etc.

once this is merged it just needs submitting to packagist for publishing.

### CODE REVIEW

**Comment by softwarespot** [comment]
So now we have two locations to update? What is the reason for the examples folder?

**Comment by anthonysomerset** [comment]
this can be tested manually without uploading to packagist (or merging) using the following composer file in your application folder of a CI install

https://gist.github.com/anthonysomerset/ab58a76a6f29e95073d0

i've just taken the default one that comes with CI 3 and added the require for codeigniter-restserver and then utlised the override of repo for custom work

**Comment by anthonysomerset** [comment]
example folder is just to provide an example implementation - i haven't done anything but copy the files from application to example - we would actually have to further clean it up as we don't actually need to add the libraries manually in an example (unless you didn't use composer to start with)

**Comment by softwarespot** [comment]
Okay, but if I update the main library, I still have two locations to update. So if only an example why is it being submitted to the master branch? Also you're autoloading everything in application/libraries, though what if someone doesn't want to autoload a particular library?

I don't believe this PR to be suitable for commiting, as ideally CI RESTful Server should be made into a standalone package.

I will wait though to see what others say.

**Comment by ivantcholakov** [comment]
I have seen earlier suggestions about the so called "Composer support", I can say that I am totally against about the idea. I am fine with the current structure of the project.

**Comment by anthonysomerset** [comment]
If you update the lib, the examples only need to be updated if the change is significant enough that change of implementation needed - its just separating example code from the actual code.

on the auto load - its only loading Format and REST_Server classes as those are the only classes composer finds in the application/libraries folder but yes it would include others if you added them there - this could easily be removed by removing the classmap in composer.json but then you would be forced to require the file again at the top of your controllers just like if you manually install it without using composer

**Comment by anthonysomerset** [comment]
ivantcholakov - your point is well noted - thats why i tried to avoid any "structure" changes so that you could still install it manually if that was your personal preference - adding composer support is purely an added convenience for those that use it already within Codeigniter otherwise - its very possible to be able to support both preferred install methods with only negligible overhead (maintaining the composer.json file)

**Comment by anthonysomerset** [comment]
any reason this was closed with no comment?

**Pull request closed without merging**
