### PR TITLE
Fix - don't call API endpoint if request is not valid.

### PR DESCRIPTION
**Pull request by benyaminshoham**
Remap function is testing for several cases of invalid requests. In some cases it "return"s when validation fails. In other cases it just adds an error response, and continue to execute. This cause endpoints to be called for failed requests (unauthorized, unauthenticated, invalid params etc').

I added a validation flag, fliping it in relevant places, and testing it at the end, before calling the endpoint.

### CODE REVIEW

**Comment by Rhino12343** [comment]
Can I make a little suggestion.

I have adjusted your fix a little to force the ability to have both api key and basic authentication.

if you have the is_valid_request as a class variable you can then set it in the _force_login function when the login is incorrect.

I found that if you have a valid API key but not a valid basic authentication it'll just let you through.

I want both to be correct.

**Comment by benyaminshoham** [comment]
@Rhino12343 I get it you want basic auth to be valid as well. I'm not sure if everyone else writing APIs will want that too. An API may have clients that are not web-based, like other APIs. In that case one might want to authenticate only with a key. Do you have an idea if the REST standard says anything about that issue?

**Comment by Rhino12343** [comment]
@benyaminshoham Unfortunately I am not sure about the REST standards.

For me personally it adds further security, if it were to be added in with a config in the application/config/rest.php to specify whether or not to use strict api key and other authentication that could be an option.

Thus when the option for api key and other authentication is enabled you can set it up to be strict or not, so in the _force_login function just have an if around the setting of is_valid_request to check the config value.

Hope this makes sense.

**Comment by benyaminshoham** [comment]
@Rhino12343 I totally agree. If you can share your version of the fix in the comments here, I'll merge the two solutions + a config option into this PR.

**Comment by Rhino12343** [comment]
Hi, Sorry for the delay.

Below is what I've done for the config and the  rest controller.

/application/config/rest.php:140
```
$config['allow_auth_and_keys'] = TRUE;
$config['strict_api_and_auth'] = TRUE; // force the use of both api and auth before a valid api request is made
```

/vendor/chriskacerguis/codeigniter-restserver/application/libraries/REST_Controller.php:344

`private $is_valid_request = TRUE;`

/vendor/chriskacerguis/codeigniter-restserver/application/libraries/REST_Controller.php:632

```
    public function _remap($object_called, $arguments = [])
    {
        // Should we answer if not over SSL?
        if ($this->config->item('force_https') && $this->request->ssl === FALSE)
        {
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unsupported')
                ], self::HTTP_FORBIDDEN);

            $this->is_valid_request = false;
        }

        // Remove the supported format from the function name e.g. index.json => index
        $object_called = preg_replace('/^(.*)\.(?:'.implode('|', array_keys($this->_supported_formats)).')$/', '$1', $object_called);

        $controller_method = $object_called.'_'.$this->request->method;
            // Does this method exist? If not, try executing an index method
            if (!method_exists($this, $controller_method)) {
                    $controller_method = "index_" . $this->request->method;
                    array_unshift($arguments, $object_called);
            }

        // Do we want to log this method (if allowed by config)?
        $log_method = ! (isset($this->methods[$controller_method]['log']) && $this->methods[$controller_method]['log'] === FALSE);

        // Use keys for this method?
        $use_key = ! (isset($this->methods[$controller_method]['key']) && $this->methods[$controller_method]['key'] === FALSE);

        // They provided a key, but it wasn't valid, so get them out of here
        if ($this->config->item('rest_enable_keys') && $use_key && $this->_allow === FALSE)
        {
            if ($this->config->item('rest_enable_logging') && $log_method)
            {
                $this->_log_request();
            }

            // fix cross site to option request error
            if($this->request->method == 'options') {
                exit;
            }

            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => sprintf($this->lang->line('text_rest_invalid_api_key'), $this->rest->key)
                ], self::HTTP_FORBIDDEN);

            $this->is_valid_request = false;
        }

        // Check to see if this key has access to the requested controller
        if ($this->config->item('rest_enable_keys') && $use_key && empty($this->rest->key) === FALSE && $this->_check_access() === FALSE)
        {
            if ($this->config->item('rest_enable_logging') && $log_method)
            {
                $this->_log_request();
            }

            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_api_key_unauthorized')
                ], self::HTTP_UNAUTHORIZED);

            $this->is_valid_request = false;
        }

        // Sure it exists, but can they do anything with it?
        if (! method_exists($this, $controller_method))
        {
            $this->response([
                    $this->config->item('rest_status_field_name') => FALSE,
                    $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unknown_method')
                ], self::HTTP_METHOD_NOT_ALLOWED);

            $this->is_valid_request = false;
        }

        // Doing key related stuff? Can only do it if they have a key right?
        if ($this->config->item('rest_enable_keys') && empty($this->rest->key) === FALSE)
        {
            // Check the limit
            if ($this->config->item('rest_enable_limits') && $this->_check_limit($controller_method) === FALSE)
            {
                $response = [$this->config->item('rest_status_field_name') => FALSE, $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_api_key_time_limit')];
                $this->response($response, self::HTTP_UNAUTHORIZED);

                $this->is_valid_request = false;
            }

            // If no level is set use 0, they probably aren't using permissions
            $level = isset($this->methods[$controller_method]['level']) ? $this->methods[$controller_method]['level'] : 0;

            // If no level is set, or it is lower than/equal to the key's level
            $authorized = $level <= $this->rest->level;
            // IM TELLIN!
            if ($this->config->item('rest_enable_logging') && $log_method)
            {
                $this->_log_request($authorized);
            }
            if($authorized === FALSE)
            {
                // They don't have good enough perms
                $response = [$this->config->item('rest_status_field_name') => FALSE, $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_api_key_permissions')];
                $this->response($response, self::HTTP_UNAUTHORIZED);

                $this->is_valid_request = false;
            }
        }

        //check request limit by ip without login
        elseif ($this->config->item('rest_limits_method') == "IP_ADDRESS" && $this->config->item('rest_enable_limits') && $this->_check_limit($controller_method) === FALSE)
        {
            $response = [$this->config->item('rest_status_field_name') => FALSE, $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_ip_address_time_limit')];
            $this->response($response, self::HTTP_UNAUTHORIZED);

            $this->is_valid_request = false;
        }

        // No key stuff, but record that stuff is happening
        elseif ($this->config->item('rest_enable_logging') && $log_method)
        {
            $this->_log_request($authorized = TRUE);
        }

        // Call the controller method and passed arguments
        try
        {
            if ($this->is_valid_request) {
                call_user_func_array([$this, $controller_method], $arguments);
            }
        }
        catch (Exception $ex)
        {
            if ($this->config->item('rest_handle_exceptions') === FALSE) {
                throw $ex;
            }

            // If the method doesn't exist, then the error will be caught and an error response shown
                $_error = &load_class('Exceptions', 'core');
                $_error->show_exception($ex);
        }
    }

```
/vendor/chriskacerguis/codeigniter-restserver/application/libraries/REST_Controller.php:2152
```
        if ($this->config->item('strict_api_and_auth') === true) {
            $this->is_valid_request = false;
        }

        // Display an error response
        $this->response([
                $this->config->item('rest_status_field_name') => FALSE,
                $this->config->item('rest_message_field_name') => $this->lang->line('text_rest_unauthorized')
            ], self::HTTP_UNAUTHORIZED);
```

I hope this all makes sense please let me know if you have any questions and I'll do my best to answer them 

Thanks for considering this to add into your PR

Adrian Bean

**Comment by vfranchi** [comment]
Thanks for the fix, I was having the same issue with key authentication. I'm using your Rest_Controller now.

**Pull request merged**
