### PR TITLE
Add http status codes

### PR DESCRIPTION
**Pull request by Tjoosten**
I implemented all the http status code into constants. It is way more easier to use.

### CODE REVIEW

**Comment by softwarespot** [comment]
I believe it would have been more appropriate to do a git fetch first and then submit the PR.

**Comment by Tjoosten** [comment]
@softwarespot documentation i will regenerate that in a sec. And the representation of the codes i tried that within the constant his name.

**Comment by softwarespot** [comment]
I was thinking in terms of intellisense, as not everybody is aware of what NO_CONTENT is for. Just saves time have to flip in and out of the browser.

@offtopic@ This is one thing I noticed with the library, the lack of documentation or sufficient documentation to the say the least. I am still not satisfied with what I have done, but in time, in time.

**Comment by Tjoosten** [comment]
can u explain more plz

**Comment by softwarespot** [comment]
The reason I had doc comments above the constants before, is in various IDEs that can parse PHP doc comments, you have a short description as to the purpose of the like of NO_CONTENT or CONFLICT. It's always good practice to document the purpose of a constant, just like a function.

**Comment by Tjoosten** [comment]
make a pr for it i should say

**Pull request merged**
