### PR TITLE
Making it third_party

### PR DESCRIPTION
**Pull request by sierrafayad**
I think we need to update the installation segment on the docs

### CODE REVIEW

**Comment by Hanisch-IT** [comment]
i think we should chose if we want to make this package available as a composer package or as a 3rd party library. We cant do both

**Comment by chriskacerguis** [comment]
@Hanisch-IT good point.  @sierrafayad what do you think?  Would composer work for you?  It seems to have become the standard...but, I would love your opinion.

**Comment by sierrafayad** [comment]
I will prefer it as a composer, and then i will start adding the
modifications i have made.

I think that would be easy

**Comment by chriskacerguis** [comment]
Sounds like a plan!  Super excited to get your PR @Hanisch-IT

**Comment by Hanisch-IT** [comment]
sry gyus, were very busy last weeks. I try to do it in the next few days

**Comment by chriskacerguis** [comment]
Closing this in favor of @Hanisch-IT PR

**Pull request closed without merging**
