### PR TITLE
Development

### PR DESCRIPTION
**Pull request by DJEDAINI**
Want to contribute with you

### CODE REVIEW

**Comment by chriskacerguis** [comment]
I'm not really sure what you are doing with this PR.  Could you please provide some context?

**Comment by DJEDAINI** [comment]
I had  some  changes and updates to and them To the repo
I and the  token based  authentification  with jwt To the rest api

Le 15 sept. 2017 16:38, "Chris Kacerguis" <notifications@github.com> a
écrit :

**Comment by chriskacerguis** [comment]
Ahhh...well, that PR looks a bit message...perhaps you could rebase and just submit your changes (and not the whole dev branch)?  Going to close this, but I welcome a PR with just your changes.

**Comment by DJEDAINI** [comment]
please tell me how to push the changes i made ?

**Comment by Hanisch-IT** [comment]
Hi @DJEDAINI,

i think the easiest way is to do a new fork from master, do your changes theire and then create a PR.

If you dont have a updated master you will commit all the changes between your version and the version of this repo.
Before you start working, make sure your master is up to date to the master of this repo.

**Pull request closed without merging**
