### PR TITLE
Verify required params

### PR DESCRIPTION
**Pull request by TarikHuber**
I don't know if there is a easy way to check if required params are in the api call. If not I'm using this but if so let me know how to use it.

Usage in controller:

$this->verify_required_params(array('name','number'));

### CODE REVIEW

**Comment by lagaisse** [comment]
Hello,

Why don't you use form_validation from CI against the args array ?

**Comment by TarikHuber** [comment]
The idea with the form validation is very good. I am new to CodeIgnitor and
need a little bit more practice. Such suggestions from CI seniors are
greate for fast evaluation.

But how do I get the validation error in the api control?

2015-08-26 12:42 GMT+02:00 Kevin Lagaisse <notifications@github.com>:

> Hello,
>
> Why don't you use form_validation from CI against the args array ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chriskacerguis/codeigniter-restserver/pull/541#issuecomment-134941391>
> .
>



-- 
Ing. Tarik Huber
Sudetenplatz 5
Freilassing 83395
Mob: 0049 152 318 413 02
E-Mail: tarik.huber@ics-logistik.com

**Comment by softwarespot** [comment]
I have only been using PHP since May 2015, so I am not a guru (yet). No idea is a bad idea, just not every day has a place in the library.

In regards to your question, look at form_validation on the CI doc site and search set_data(). This should give you some idea of how to validate POST data without a form.

**Comment by TarikHuber** [comment]
Using the form_validation detects if something is not as it should be but I
can't figure out how to get the error message from the form_validation :(
 the post funciton of codeigniter are making things easier but still i have
to check every one to send a specific message if a arg is missing.

2015-08-26 13:26 GMT+02:00 SoftwareSpot Apps <notifications@github.com>:

> I have only been using PHP since May 2015, so I am not a guru (yet). No
> idea is a bad idea, just not every day has a place in the library.
>
> In regards to your question, look at form_validation on the CI doc site
> and search set_data(). This should give you some idea of how to validate
> POST data without a form.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chriskacerguis/codeigniter-restserver/pull/541#issuecomment-134955118>
> .
>



-- 
Ing. Tarik Huber
Sudetenplatz 5
Freilassing 83395
Mob: 0049 152 318 413 02
E-Mail: tarik.huber@ics-logistik.com

**Comment by softwarespot** [comment]
Perhaps ask on the CI Forum instead. This is what it's for.

**Pull request closed without merging**
