### PR TITLE
Profiling feature added to master

### PR DESCRIPTION
**Pull request by zgmunshi**
@Hanisch-IT @chriskacerguis Profiling feature added to master.Kindly merge

### CODE REVIEW

**Comment by Hanisch-IT** [comment]
Hi @zgmunshi,

i have one thing to mind. You add the config.php to this PR. Maybe that will be a problem, because that would overwrite existing config.php files. Maybe we should only update the documentation and not include the whole config.
What do you think?

**Comment by chriskacerguis** [comment]
@zgmunshi @Hanisch-IT or perhaps we should rename the config.php file to config.php.example?

**Comment by Hanisch-IT** [comment]
And also add the needed config to the documentation. 

I wonder why he/she commited the config.php because is nothing changed im comparison to the default one.

I think we just need to document that
```php
$config['enable_hooks'] = FALSE;
```

has to be

```php
$config['enable_hooks'] = TRUE;
```

if someone wont to use profiler

**Comment by zgmunshi** [comment]
Hi @Hanisch-IT @chriskacerguis ,
I agree on renaming the file to config.php.sample

Regarding committing the config.php the added  config parameter is 
`$config['enable_profiling'] = FALSE;
`
which is responsible for enabling /disabling the profiler as there might be various other hooks defined in the project & that should not unable the profiler unless you explicitly enable it.

Also i will add this to documentation.

Thanks.

**Comment by zgmunshi** [comment]
@Hanisch-IT @chriskacerguis I have added the settings to readme.
Let me know if anything further needs to be done. I was checking for documentation too but didn't find any section for config so added to readme.

**Comment by zgmunshi** [comment]
@Hanisch-IT @chriskacerguis When will this be merged ?

**Comment by Hanisch-IT** [comment]
Hi @zgmunshi, give @chriskacerguis some time. He is doing that in his free time so we have to wait till he has the time to check and merge this pr.

**Pull request merged**
