### PR TITLE
Fixed date library being loaded, re-factored JS and throw exceptions

### LINKED ISSUE #536: _log_request() fails if Date Helper not auto loaded
At the time of writing line number 971 of REST_Controller.php looks like this:

`'time' => now(), // Used to be: function_exists('now') ? now() : time()`

The reason for the function_exists() check that has recently been removed is the now() function is part of the CodeIgniter Date Helper which, while available as part of the CI core, may not be loaded for any particular project.

If usage is going to be standardized to one or the other I think either of the native mktime() /  time()  functions would be preferable to the helper function. Or the Date Helper should be listed as a requirement to use this library. Or the Date Helper should be explicitly loaded by this library. Or the version of this line using function_exists() should be used.

### PR DESCRIPTION
**Pull request by softwarespot**
Closes #536 and references #474

### CODE REVIEW

**Comment by kenjis** [comment]
@softwarespot it seems you added unrelated commits into this PR.

**Comment by softwarespot** [comment]
True, and normally I would create a separate PR. Thanks,

**Comment by kenjis** [comment]
It happened because you had not created a new branch for this PR.
You use `master` branch. So GitHub adds your new commits in `master` branch to this PR, too.

**Comment by softwarespot** [comment]
Thanks. I will also do that for this repository as well.

**Comment by softwarespot** [comment]
I have created separate branches. Closing.

**Pull request closed without merging**
